config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "links#index"

  get "/links", to: "links#new"
  post "/links", to: "links#create"

  get "/link/:id/comments", to: "comments#new", as: "comments_new"
  post "/link/:id/comments", to: "comments#create", as: "comments_create"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :link
  belongs_to :user
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :links
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @link = Link.find(params[:id])
    @all_comments = @link.comments
    render :comments
  end

  def create
    @link = Link.find(params[:id])

    if current_user
      @comment = @link.comments.create(content: params[:content],
                                       user_id: current_user)
      flash[:notice] = 'Comment posted.'
    else
      flash[:alert] = 'Only logged in users can post comments.'
    end
    redirect_to comments_new_path(@link)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all.order(created_at: :DESC)
    # binding.pry
    render :index
  end

  def new
    if current_user
      # @user = User.create(email: params[@user])
      render :links
    else
      redirect_to new_user_session_path
    end
  end

  def create
    @link = Link.create(destination: params[:destination],
                              title: params[:title],
                              created_at: DateTime.now)
    redirect_to :root
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/comments.html.erb
<h1> LinkMarket - Comment Page </h1>

<div>
  <%= link_to "Back", :root, class: 'btn btn-primary btn-xs' %>
</div>

<div>
  <%= link_to "Home", :root %>

<h2><%= link_to @link.title, @link.destination %></h2>

<%= form_tag(comments_create_path) do %>
  <div class="form-group">
    <%= label_tag(:content, "Comment: ") %>
    <br/>
    <%= text_area_tag(:content, nil, rows: 20, cols: 60) %>
  </div>

  <div><%= submit_tag 'Save', class: 'btn btn-danger' %></div>

  <div>
    <ul>
    <% @all_comments.each do |comment| %>
      <li><%= comment.content %></li>
      <li><%= <time datetime="YYYY-MM-DDThh:mm:ssTZD">comment.created_at %></li>
      DATETIME - format: YYYY-MM-DD HH:MI:SS
      <br>
    <% end %>
    </ul>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Linkmarket</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/links/index.html.erb
<div class="container">
  <div class="row">
    <h1> LinkMarket - Homepage </h1>
  </div>
  <div class="nav-bar">
    <div class="row">
      <p class="top-row">
      <%= link_to "Login", new_user_session_path, class: 'btn btn-info, bg-info' %>
      <%= link_to "Register", new_user_registration_path, class: 'btn btn-info' %>
      <%= link_to "Post Link", links_path, class: 'btn btn-info' %>

      <% if current_user %>
      <%= link_to "Log Out", destroy_user_session_path,class: 'btn btn-primary',
            method: :delete %>
      <% end %>
      </p>
    </div>
  </div>

<div class="links">
  <ol>
  <% @links.each do |link| %>
    <li>
      <%= link_to link.title, link.destination, class:"text-info" %> <br>
      <%= link_to "Comments", comments_new_path(link), class: 'btn btn-primary btn-xs' %><br>
    </li>
  <% end %>
  </ol>
</div>
</div>

app/views/links/links.html.erb
<h1> LinkMarket - Post a Link Page </h1>

<%= form_tag(links_path) do %>
  <div>
    <%=label_tag(:title, "Title:")%>
    <%=text_field_tag(:title, nil, size: 40)%>
    <br>
    <%=label_tag(:destination, "Link:")%>
    <%=url_field_tag(:destination, nil, size: 40)%>
  <div><%= submit_tag 'Save', class: 'btn btn-danger' %></div>
<% end %>

<div>
  <%= link_to "Back", :root, class: 'btn btn-primary btn-xs' %>
</div>

app/views/users/login.html.erb
<h1> Login </h1>

<%= form_tag(@action, method: :post) do %>

  <div>
    <%= label_tag(:email, "Email: ") %>
    <%= text_field_tag(:email, nil, size: 40) %>
  </div>

  <div>
    <%= label_tag(:password, "Password: ") %>
    <%= password_field_tag(:password) %>
  </div>

  <%= submit_tag("Login") %>
<% end %>